export const chinese: Record<string, string> = {
  "Something went wrong on our side. Please try again.": "服务暂时未能完成请求，请重试。",
  "Something went wrong.": "请求未能完成，请重试。",
  "Margin impact": "毛利影响",
  "Reply": "回复", "Previous reply": "上一条回复", "Next reply": "下一条回复",
  "Close activity": "关闭活动记录", "Steps": "执行步骤", "new": "新增",
  "Home": "首页", "Catalog": "商品", "Orders": "订单", "Inventory": "库存",
  "Merchant workspace": "商家工作台", "Store manager": "店铺经理", "Operator": "操作员",
  "Business memory": "经营记忆", "Portal views": "工作台页面", "Assistant": "经营助手",
  "Hide assistant": "收起助手", "Show assistant": "打开助手", "Working": "处理中",
  "Merchant assistant": "经营助手",
  "Ask about performance, inventory, pricing, or campaigns.": "询问经营表现、库存、价格或营销活动。",
  "What needs my attention this morning?": "今天早上有哪些事项需要我关注？",
  "How did sales do this week compared to last?": "本周销量与上周相比如何？",
  "Which listings are running low on stock?": "哪些商品库存不足？",
  "Which slow movers should we mark down?": "哪些滞销商品适合降价？",
  "Message the merchant assistant": "向经营助手发送消息",
  "Ask about sales, stock, pricing…": "询问销量、库存、定价…",
  "Send": "发送", "Close": "关闭", "Activity": "活动记录",
  "Couldn't reach the demo service. Check that it is running and try again.": "无法连接演示服务，请检查服务是否已启动后重试。",
  "Awaiting approval": "待批准", "Approved": "已批准", "Dismissed": "已放弃",
  "Approve": "批准", "Dismiss": "放弃", "Applying…": "正在应用…", "Dismissing…": "正在放弃…",
  "Nothing applies until you approve.": "只有点击批准后才会应用变更。",
  "That action did not go through. Check the API and try again.": "操作未成功，请检查演示服务后重试。",
  "Before": "修改前", "After": "修改后", "Stock": "库存", "Price": "价格",
  "Status": "状态", "Short description": "简短描述", "Long description": "详细描述",
  "Content quality": "内容质量", "Title": "标题", "Proposed change": "变更提案",
  "Inventory action": "库存操作", "Listing update": "商品内容更新", "Price update": "价格更新",
  "Performance": "经营表现", "Average order": "客单价", "Sales": "销售额", "Revenue": "收入",
  "Spend": "支出", "Traffic": "访问量", "Conversion rate": "转化率", "Return rate": "退货率",
  "Click through rate": "点击率", "Needs attention": "待关注事项", "sold out": "售罄",
  "Draft restock": "准备补货", "Plan markdown": "准备降价", "Draft reply": "准备回复", "Ask why": "分析原因",
  "This week": "本周", "Last week": "上周", "Last 7 days": "近7天", "Last 30 days": "近30天",
  "You approve every change": "每项变更均由你批准", "Full screen": "全屏", "Exit full screen": "退出全屏",
  "Resize assistant panel": "调整助手面板宽度",
  "Short description.en": "简短描述（英文）", "Short description.zh": "简短描述（中文）",
  "Long description.en": "详细描述（英文）", "Long description.zh": "详细描述（中文）",
  "Title.en": "标题（英文）", "Title.zh": "标题（中文）",
  "hidden from the storefront": "顾客端已隐藏", "in stock": "件库存", "Low stock": "库存不足",
  "Slow movers": "滞销商品", "soonest to run out first": "按预计售罄时间排序",
  "stock well above the last 30 days of sales": "库存明显高于近30天销量",
  "No low-stock listings.": "没有库存不足的商品。", "No slow movers.": "没有滞销商品。",
  "Inventory alerts could not be loaded.": "无法加载库存告警，请检查演示服务。",
  "Order": "订单", "opened": "创建于", "Ask": "询问", "Open issues": "待处理问题",
  "Recent orders": "近期订单", "No open issues": "没有待处理问题",
  "No open order issues.": "没有待处理的订单问题。", "No recent orders to show.": "暂无近期订单。",
  "Order issues could not be loaded.": "无法加载订单问题，请检查演示服务。",
  "Shipped": "已发货", "Processing": "处理中", "Delivered": "已送达", "Delayed": "延误",
  "Buyer message": "买家消息", "Return spike": "退货增加", "Cancelled": "已取消",
  "Poor content": "内容较差",
  "Needs work": "待完善",
  "Good": "良好",
  "Ask about this listing": "询问此商品",
  "Pricing": "定价",
  "Missing from the listing": "商品缺失资料",
  "What buyers say": "买家评价",
  "Description": "描述",
  "Variants": "规格变体",
  "Variant": "规格",
  "Listing": "商品",
  "Category": "类别",
  "Content": "内容",
  "Ask about the catalog": "询问商品情况",
  "No listings match.": "没有符合条件的商品。",
  "In stock": "库存",
  "Sold, 30 days": "近30天销量",
  "Price from": "起售价",
  "Margin": "毛利率",
  "Close listing detail": "关闭商品详情",
  "Draft these attributes": "准备这些属性",
  "Customer-written": "顾客提供的内容",
  "Search by title, ID, or attribute": "按名称、编号或属性搜索",
  "Search listings": "搜索商品",
  "Filter listings": "筛选商品",
  "All": "全部",
  "Active": "在售",
  "Needs content": "内容待完善",
  "Inactive": "非在售",
  "Everything else": "其他商品",
  "All listings": "全部商品",
  "Could not load this listing.": "无法加载商品详情。",
  "Listings could not be loaded.": "无法加载商品列表，请检查演示服务。",
  "Paused": "已暂停",
  "Draft": "草稿",
  "Out of stock": "缺货",
  "Beauty & personal care": "美妆与个护",
  "Fitness": "健身",
  "Furniture & bedroom": "家具与卧室",
  "Grocery": "食品杂货",
  "Home & kitchen": "家居与厨房",
  "Kids' room": "儿童房",
  "Office & electronics": "办公与电子",
  "Outdoor & camping": "户外与露营",
  "Pet supplies": "宠物用品",
  "Toys & games": "玩具与游戏",
  "Travel": "旅行",
  "unit cost": "单位成本", "demand": "需求", "changed": "更新于", "high": "高", "low": "低", "steady": "平稳",
  "Slow mover": "滞销", "standard": "标准尺寸", "king": "特大尺寸", "queen": "大号尺寸", "twin": "单人尺寸",
  "ivory": "象牙色", "slate": "岩灰色", "blush": "腮红粉", "sage": "鼠尾草绿",
  "full": "双人尺寸", "amber": "琥珀色", "chestnut": "栗棕色", "espresso": "深咖色",
  "honey": "蜜糖色", "porcelain": "瓷白色", "sand": "沙色",
  "12 lb": "12磅", "15 lb": "15磅", "20 lb": "20磅",
  "rising": "上升", "falling": "下降", "wall coverage": "墙面覆盖面积", "material": "材质",
  "now": "当前", "floor": "下限", "ceiling": "上限",
  "Good morning": "早上好", "Good afternoon": "下午好", "Good evening": "晚上好", "Welcome": "欢迎",
  "Overview could not be loaded. Check that the demo service is running.": "无法加载经营概览，请检查演示服务是否已启动。",
  "Needs you today": "今日待办", "Filter attention items": "筛选待关注事项", "Slow": "滞销",
  "Nothing needs you today.": "今天没有待处理事项。", "See all": "查看全部", "From the assistant": "经营洞察",
  "All orders": "全部订单", "No orders yet.": "暂无订单。", "prior week": "上周", "prior period": "上一周期",
  "Conversion": "转化率", "Average order value": "客单价",
  "Sales: ask the assistant why": "询问销售额变化原因", "Orders: ask the assistant why": "询问订单量变化原因",
  "Conversion: ask the assistant why": "询问转化率变化原因", "Average order value: ask the assistant why": "询问客单价变化原因",
  "Review": "查看提案", "Recent changes": "近期变更",
};
