export const chinese: Record<string, string> = {
  "Home": "首页", "Catalog": "商品", "Orders": "订单", "Inventory": "库存",
  "Merchant workspace": "商家工作台", "Store manager": "店铺经理", "Operator": "操作员",
  "Business memory": "经营记忆", "Portal views": "工作台页面", "Assistant": "经营助手",
  "Hide assistant": "收起助手", "Show assistant": "打开助手", "Working": "处理中",
  "Merchant assistant": "经营助手",
  "Ask about performance, inventory, pricing, or campaigns.": "询问经营表现、库存、价格或营销活动。",
  "What needs my attention this morning?": "今天早上有哪些事项需要我关注？",
  "How did sales do this week compared to last?": "本周销量与上周相比如何？",
  "Which listings are running low on stock?": "哪些商品库存不足？",
  "Which slow movers should we mark down?": "哪些滞销商品适合降价？",
  "Message the merchant assistant": "向经营助手发送消息",
  "Ask about sales, stock, pricing…": "询问销量、库存、定价…",
  "Send": "发送", "Close": "关闭", "Activity": "活动记录",
  "Couldn't reach the demo service. Check that it is running and try again.": "无法连接演示服务，请检查服务是否已启动后重试。",
  "Awaiting approval": "待批准", "Approved": "已批准", "Dismissed": "已放弃",
  "Approve": "批准", "Dismiss": "放弃", "Applying…": "正在应用…", "Dismissing…": "正在放弃…",
  "Nothing applies until you approve.": "只有点击批准后才会应用变更。",
  "That action did not go through. Check the API and try again.": "操作未成功，请检查演示服务后重试。",
  "Before": "修改前", "After": "修改后", "Stock": "库存", "Price": "价格",
  "Status": "状态", "Short description": "简短描述", "Long description": "详细描述",
  "Content quality": "内容质量", "Title": "标题", "Proposed change": "变更提案",
  "Inventory action": "库存操作", "Listing update": "商品内容更新", "Price update": "价格更新",
  "Performance": "经营表现", "Average order": "客单价", "Sales": "销售额", "Revenue": "收入",
  "Spend": "支出", "Traffic": "访问量", "Conversion rate": "转化率", "Return rate": "退货率",
  "Click through rate": "点击率", "Needs attention": "待关注事项", "sold out": "售罄",
  "Draft restock": "准备补货", "Plan markdown": "准备降价", "Draft reply": "准备回复", "Ask why": "分析原因",
  "This week": "本周", "Last week": "上周", "Last 7 days": "近7天", "Last 30 days": "近30天",
  "You approve every change": "每项变更均由你批准", "Full screen": "全屏", "Exit full screen": "退出全屏",
  "Resize assistant panel": "调整助手面板宽度",
  "Short description.en": "简短描述（英文）", "Short description.zh": "简短描述（中文）",
  "Long description.en": "详细描述（英文）", "Long description.zh": "详细描述（中文）",
  "Title.en": "标题（英文）", "Title.zh": "标题（中文）",
};
