/** Interface copy only. Product content comes from the selected dataset. */
export const chinese: Readonly<Record<string, string>> = {
  "Assistant": "购物助手",
  "Orders": "订单",
  "Cart": "购物车",
  "Guest": "访客",
  "Ask about an order, a return, a delivery…": "询问订单、退货或配送…",
  "Ask about a product, a project, an order…": "询问商品、选购计划或订单…",
  "Popular right now": "热门商品",
  "Bestsellers and new arrivals; open one to ask about it": "畅销与新品；点开商品了解详情",
  "A tent for a first family camping trip, under $250": "第一次家庭露营，想选一顶250美元以内的帐篷",
  "Set up a home office in a small spare room for about $800": "用大约800美元，把一间小空房布置成家庭办公室",
  "Drip or espresso for busy weekday mornings?": "工作日早晨时间紧，选滴滤咖啡机还是意式咖啡机？",
  "Remember: small apartment, no outdoor storage, and a golden retriever": "请记住：我住小公寓，没有室外储物空间，养了一只金毛犬",
  "Good morning": "早上好",
  "Good afternoon": "下午好",
  "Good evening": "晚上好",
  "Hello": "你好",
  "Ask about a product, a project, an order, or a return.": "可以询问商品、选购计划、订单或退货。",
  "Nothing on the way right now. Ask about a product, a project, or a return.": "目前没有待收货订单。可以询问商品、选购计划或退货。",
  "Activity": "活动记录",
  "Send": "发送",
  "Working…": "处理中…",
  "Remove": "移除",
  "View summary": "查看结算摘要",
  "Check out": "结算",
  "Show me the checkout summary again.": "请再次显示结算摘要。",
  "Check out my cart.": "请结算我的购物车。",
  "Nothing in the cart yet.": "购物车还没有商品。",
  "Ask ACME Assistant for anything in the store.": "向购物助手询问店内的任何商品。",
  "Subtotal": "小计",
  "Ask about this cart": "询问购物车",
  "Look over my cart: anything missing or worth swapping?": "帮我看看购物车：还有遗漏或值得更换的商品吗？",
  "Free shipping on this order ✓": "此订单包邮 ✓",
  "Anything more ships free": "再加购即可包邮",
  "Out of stock": "缺货",
  "30-day returns": "30天退货",
  "programmable": "可编程",
  "Recommended": "推荐",
  "Best for:": "适合：",
  "Price difference:": "价差：",
  "Compared on:": "比较维度：",
  "Sources:": "资料来源：",
  "Ready to check out": "准备结算",
  "Not charged": "尚未扣款",
  "Tax": "税费",
  "Calculated at checkout": "结算时计算",
  "Estimated total": "预计总额",
  "Continue to checkout": "前往结算",
  "Nothing is charged here. Payment happens when you check out.": "此处不会扣款。付款在结算时完成。",
  "Shipping": "配送",
  "Free": "免费",
  "Before tax": "不含税费",
  "Before shipping and tax": "不含运费和税费",
  "standard": "标准配送",
  "delivery": "配送",
  "shipping": "运输",
  "pickup": "到店自提",
  "3\u20135 business days": "3–5个工作日",
  "Most items can be returned within 30 days of delivery for a refund to your original payment method.": "大多数商品可在送达后30天内退货，退款将退回原支付方式。",
  "Processing": "处理中",
  "Shipped": "已发货",
  "Out for delivery": "派送中",
  "Delayed": "延误",
  "Delivered": "已送达",
  "Cancelled": "已取消",
  "Return requested": "已申请退货",
  "Refunded": "已退款",
  "Ordered": "已下单",
  "Packed": "已打包",
  "Placed": "下单于",
  "Expected": "预计",
  "Arrives": "送达于",
  "Arriving": "待收货",
  "Nothing on the way": "暂无待收货订单",
  "On the way": "配送中",
  "Past": "历史订单",
  "All": "全部",
  "order": "订单",
  "Ask why": "询问原因",
  "Ask about a return": "咨询退货",
  "Ask": "询问",
  "processing": "处理中",
  "shipped": "已发货",
  "out for delivery": "派送中",
  "delayed": "延误",
  "delivered": "已送达",
  "cancelled": "已取消",
  "return initiated": "已申请退货",
  "refunded": "已退款",
  "Order": "订单",
  "Total": "合计",
  "Estimated delivery:": "预计送达：",
  "Track package": "跟踪包裹",
  "The original delivery estimate was missed": "未能按原预计时间送达",
  "No items to show for this step.": "此步骤暂无商品。",
  "Planned picks": "计划选购",
  " (cheapest option per step)": "（每步按最低价选项计算）",
  "added sugar": "添加糖",
  "armrests": "扶手",
  "art": "图案",
  "assembly": "组装",
  "backing": "背衬",
  "bake": "烘烤",
  "bin": "收纳箱",
  "blackout": "遮光",
  "blend": "混合成分",
  "board": "板面",
  "brightness": "亮度",
  "capacity": "容量",
  "care": "保养",
  "clearance": "底部间隙",
  "color": "颜色",
  "colors": "颜色",
  "cook time": "烹饪时间",
  "count": "数量",
  "cover": "外罩",
  "cruelty free": "无动物测试",
  "details": "详情",
  "dimensions": "尺寸",
  "doors": "门数",
  "filling": "填充物",
  "finish": "表面处理",
  "finished size": "完成尺寸",
  "floor area": "底面积",
  "foam": "泡棉",
  "handle": "手柄",
  "height": "高度",
  "idea cards": "创意卡",
  "increments": "调节步幅",
  "largest": "最大尺寸",
  "largest decal": "最大贴纸",
  "layers": "层数",
  "liner": "内衬",
  "lock": "锁具",
  "marinade time": "腌制时间",
  "material": "材质",
  "max dog": "适用犬只最大体重",
  "mounting": "安装方式",
  "noise": "噪声",
  "noodles": "面条",
  "packed size": "收纳尺寸",
  "panels": "片数",
  "peak height": "最高高度",
  "pieces": "件数",
  "pile height": "绒高",
  "power": "功率",
  "power delivery": "供电",
  "prep": "准备方式",
  "rainfly": "外帐",
  "recline": "后仰调节",
  "refresh": "刷新率",
  "removal": "移除方式",
  "resolution": "分辨率",
  "rims": "轮缘",
  "roast": "烘焙程度",
  "runtime": "运行时长",
  "safety": "安全",
  "sauce": "酱料",
  "seat height": "座高",
  "serves": "份数",
  "shades": "色号",
  "shell": "外壳",
  "size": "尺寸",
  "sizes": "尺寸",
  "source": "来源",
  "spf": "防晒系数",
  "suction": "吸力",
  "surface": "适用表面",
  "trays": "托盘",
  "trial": "试用期",
  "type": "类型",
  "vegan": "纯素",
  "volume": "容积",
  "warranty": "保修",
  "wear": "持妆时间",
  "weight": "重量",
  "weight capacity": "承重",
  "weight range": "重量范围",
  "Durability": "耐用性",
  "Play value": "可玩性",
  "Age fit": "年龄适配",
  "Easy cleanup": "易收拾",
  "Easy setup": "易安装",
  "Looks as pictured": "与图片一致",
  "Kid appeal": "儿童喜爱度",
  "Pet comfort": "宠物舒适度",
  "Easy to clean": "易清洁",
  "Sizing": "尺寸适配",
  "Build quality": "做工",
  "Performance": "性能",
  "Value": "性价比",
  "Setup": "安装搭建",
  "Comfort": "舒适度",
  "Reliability": "可靠性",
  "Weather resistance": "耐候性",
  "Pack size": "收纳体积",
  "Grip": "握持感",
  "Packability": "便携收纳",
  "Wheels & handle": "轮子与拉杆",
  "Capacity": "容量",
  "Gentle formula": "温和配方",
  "Scent": "气味",
  "Results": "效果",
  "Assembly": "组装",
  "As pictured": "与图片一致",
  "Freshness": "新鲜度",
  "Taste": "口味",
  "Packaging": "包装",
  "Quality": "品质",
  "As described": "与描述一致",
  "amber": "琥珀色",
  "blush": "腮红粉",
  "chestnut": "栗色",
  "espresso": "浓咖啡色",
  "full": "双人尺寸（full）",
  "honey": "蜂蜜色",
  "ivory": "象牙色",
  "king": "特大尺寸（king）",
  "porcelain": "瓷白色",
  "queen": "大号尺寸（queen）",
  "sage": "鼠尾草绿",
  "sand": "沙色",
  "slate": "岩灰色",
  "twin": "单人尺寸（twin）",
  "Options": "规格选项",
  "Collapse details": "收起详情",
  "Loading details…": "正在加载详情…",
  "Scroll to previous products": "查看前面的商品",
  "Scroll to more products": "查看更多商品",
  "Sitting near the low end of its own range": "接近该商品自身价格区间的低位",
  "Sitting near the high end of its own range": "接近该商品自身价格区间的高位",
  "Sitting in the typical band of its own range": "处于该商品自身价格区间的常见水平",
  "Preference": "偏好",
  "Rule": "规则",
  "About you": "关于你",
  "Edit": "编辑",
  "Forget": "删除记忆",
  "Correct this": "修改这条记忆",
  "That could not be saved. Keep it to a preference or a standing rule.": "无法保存，请只填写偏好或长期规则。",
  "Save": "保存",
  "Cancel": "取消",
  "New this session": "本次会话新增",
  "Saved": "保存于",
  "Nothing saved yet.": "尚无记忆。",
  "Only preferences and standing rules are kept. Card, account, phone, and email details are refused.": "仅保存偏好和长期规则，不保存银行卡、账户、电话和邮箱信息。",
  "ACME Subscription member": "ACME订阅会员",
  "Views": "页面",
  "Memory": "记忆",
  "Reply": "回复",
  "Previous reply": "上一条回复",
  "Next reply": "下一条回复",
  "Close activity": "关闭活动记录",
  "Steps": "执行步骤",
  "No replies yet.": "尚无回复。",
  "No tool calls this reply.": "本次回复未调用工具。",
  "new": "新增",
  "Input": "输入",
  "Result": "结果",
  "Result (excerpt)": "结果（节选）",
  "running\u2026": "运行中…",
  "error": "错误",
  "ok": "成功",
  "held \u00b7 provenance gate": "暂停 · 来源校验",
  "held \u00b7 approval gate": "暂停 · 审批校验",
  "held \u00b7 guardrail": "暂停 · 保护规则",
  "held \u00b7 safety gate": "暂停 · 安全校验",
  "Searching the catalog…": "搜索商品目录…",
  "Reading the details…": "读取商品详情…",
  "Checking the policies…": "查询政策…",
  "Looking up your orders…": "查询订单…",
  "Checking delivery and pickup options…": "查询配送与自提选项…",
  "Checking the cart…": "查看购物车…",
  "Updating the cart…": "更新购物车…",
  "Preparing your order summary…": "准备结算摘要…",
  "Reading your profile…": "读取用户资料…",
  "Recalling what you've told me…": "回想你提供的信息…",
  "Saving that for next time…": "保存信息供下次使用…",
  "Loading…": "正在加载…",
  "Searching the web…": "搜索网络…",
  "Reading the business snapshot…": "读取经营概况…",
  "Querying metrics…": "查询经营指标…",
  "Searching the listings…": "搜索商品…",
  "Reading the listing…": "读取商品信息…",
  "Checking inventory alerts…": "检查库存预警…",
  "Checking order issues…": "检查订单问题…",
  "Reading the pricing context…": "读取定价情况…",
  "Reading campaign performance…": "读取活动表现…",
  "Checking pending changes…": "检查待审批变更…",
  "Running the analysis…": "执行分析…",
  "Applying the change…": "应用变更…",
  "Discarding the change…": "放弃变更…",
  "Composing the answer…": "整理回答…",
  "Staging a change for review…": "准备变更供审核…",
  "Latest": "最新消息",
  "Close": "关闭",
  "Standard size": "标准尺寸",
  "Couldn't reach the demo service. Check that it is running and try again.": "无法连接演示服务，请确认服务已启动后重试。",
};
